### ISSUE TITLE
Notations that contain 2 or more digits from the numbered list are truncated

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#419]
[Affected versions]:
- Firefox 57 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.9.0b2 build with CKeditor) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click on "Numbered List" button.
3. Type something then Press "Enter" key.
4. Repeat step 3 for 99 more times.
5. Observe the numbers that contain 2 or more digits.

[Expected result]:
- Notations are fully displayed.

[Actual result]:
- Notations are truncated.

[Additional Notes]:
- The issue is not reproducible with the "Firefox Notes" master build.
- Attached a screen recording of the issue:

![truncated numbers](https://user-images.githubusercontent.com/26000308/33074438-de8fa786-cece-11e7-8012-a4e05dcd79ce.gif)

**Comment by vladikoff** [comment]
This should be fixed 👍

**Comment by SoftVision-CarmenFat** [comment]
Hi @vladikoff ,

Tested this issue with the latest Notes 1.9.0dev (custom build 2017-11-24). It seems that the issue is fixed for the notations containing 2 or 3 digits, but for the notations that contain 4 digits, the issue is still reproducible, as seen in the image below. 

Should this still be considered as an issue or should we consider it as a won't fix, given the large amount of items in the list?

![1000](https://user-images.githubusercontent.com/26000308/33212366-5c51cd08-d12b-11e7-9e2c-6a6e4bd70280.png)

**Comment by Natim** [comment]
I asked @vladikoff about that yesterday telling him we should probably give a bit more space to the list items and he told me due to the limited space of the sidebar we should not worry about it.

**Comment by vladikoff** [comment]
yea this is a wontfix for now, but we might revisit it
