### ISSUE TITLE
The "Sync Your Notes" button is slightly moving when it's being clicked

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#526]
[Affected versions]:
- Firefox 57.0.2 and up

[Affected Platforms]:
- All Windows
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest "Firefox Notes" add-on version (2.2.0dev custom build from 12.19.2017) installed.
- You are already logged into "Firefox Notes" account.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites.
2. Click "Sync Your Notes" button and observe the behavior.

[Expected result]:
- Sync button doesn't move and the animation begins.

[Actual result]:
- Sync button is slightly moving before the animation begins.

[Notes]:
- This issue is also reproducible when you try to reconnect to sync or when you try to log in.
- Here is a screen recording of the issue:
![moving sync up button](https://user-images.githubusercontent.com/31244235/34165168-339cc058-e4e4-11e7-8896-24391f1f2178.gif)

**Comment by himanish-star** [comment]
I would surely like to look into this.

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using "Firefox Notes" add-on v2.2.0dev custom build from 01.10.2018, on latest Nightly build 59.0a1 (2018-01-10), on Windows 10x64 and Ubuntu 14.04 x64.

**Comment by Softvision-CristinaBadescu** [comment]
This issue is still reproducible using Firefox Notes v3.0.0dev, on latest Nightly build 60.0a1 (2018-02-20), on Windows 10 x64 and Arch Linux 4.12. Considering this, I'm going to reopen the issue.

**Comment by vladikoff** [comment]
Should be fixed via 

https://github.com/mozilla/notes/pull/756
https://github.com/mozilla/notes/pull/752

Let us know! It doesn't jump for me in OS X anymore...

**Comment by Softvision-CristinaBadescu** [comment]
As I've mentioned in the affected platforms, only on Windows and Linux OS'es this issue is reproducible. Indeed, on Mac OS'es this behavior does not occur.

I'm going to reopen this, since it's still reproducible using Firefox Notes v3.1.0dev (custom built on 2018-03-12), on latest Nightly build 60.0a1 (2018-03-11), on Windows 10 x64 and Linux 4.12.

**Comment by vladikoff** [comment]
Merged a fix for it, will be part of 3.1 release so we can test 👍

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using Firefox Notes v3.1.0dev, on latest Nightly build 60.0a1 (2018-03-13), on Windows 10 x64 and Arch Linux 4.12.
Thanks for the fix!

**Comment by vladikoff** [comment]
SuccesS!!

**Comment by vladikoff** [comment]
success!
